name: PHP tests
on: [push, pull_request]

jobs:
  php-linter:
    name: PHP Syntax check 5.6|7.2|7.3|7.4|8.0|8.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: PHP syntax checker 5.6
        uses: prestashop/github-action-php-lint/5.6@master

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master

      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master

      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: PrestaShop/.github/.github/actions/php-ci/php-cs@master
        with:
          php-version: '7.4'

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-version: ['1.7.7.x', '1.7.8.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: ${{ github.event.repository.name }}
      
      - uses: Quetzacoalt91/.github/.github/actions/php-ci/phpstan@cache
        with:
          php-version: '7.4'
          presta-version: ${{ matrix.presta-version }}
          module-name: ${{ github.event.repository.name }}
          phpstan-level: '5'
          phpstan-config: 'tests/phpstan/phpstan-${{ matrix.presta-version }}.neon'
          phpstan-version: '^0.12'
          composer-version: '2'

  # Run PHPStan against the module and a PrestaShop release
  phpstan-legacy:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['1.7.1.2', '1.7.2.5', '1.7.3.4', '1.7.4.4', '1.7.5.1', '1.7.6']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Checkout
        uses: actions/checkout@v5

      - run: composer install

      # Docker images prestashop/prestashop may be used, even if the shop remains uninstalled
      - name: Execute PHPStan on PrestaShop (Tag ${{ matrix.presta-versions }})
        run: ./tests/phpstan.sh ${{ matrix.presta-versions }}
